"""create extraction values table

Revision ID: 29779a714e20
Revises: d8885e66aab9
Create Date: 2026-09-14 02:08:59.442716

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29779a714e20'
down_revision: str | Sequence[str] | None = 'd8885e66aab9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_field_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['extraction_field_id'], ['extraction_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation_id', 'extraction_field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extraction_values')
    # ### end Alembic commands ###
