"""create citations table

Revision ID: 348d28e9eeff
Revises: 620754dfd90a
Create Date: 2026-09-13 02:12:23.760170

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348d28e9eeff'
down_revision: str | Sequence[str] | None = '620754dfd90a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_project_id'], ['review_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    # ### end Alembic commands ###
