"""create criteria table

Revision ID: 620754dfd90a
Revises: 8cfd77348211
Create Date: 2026-09-13 01:51:37.487701

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620754dfd90a'
down_revision: str | Sequence[str] | None = '8cfd77348211'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_project_id', sa.Uuid(), nullable=False),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('intervention', sa.String(), nullable=True),
    sa.Column('comparison', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('exclusion_rules', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['review_project_id'], ['review_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criteria')
    # ### end Alembic commands ###
