"""create possible duplicates table

Revision ID: 9fab29665518
Revises: 12bd2c6f5eea
Create Date: 2026-09-14 22:51:34.109245

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9fab29665518'
down_revision: str | Sequence[str] | None = '12bd2c6f5eea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possible_duplicates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_project_id', sa.Uuid(), nullable=False),
    sa.Column('survivor_citation_id', sa.Uuid(), nullable=False),
    sa.Column('loser_citation_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loser_citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['review_project_id'], ['review_projects.id'], ),
    sa.ForeignKeyConstraint(['survivor_citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('possible_duplicates')
    # ### end Alembic commands ###
