"""create full text suggestions tables

Revision ID: d8885e66aab9
Revises: 879e067e67d2
Create Date: 2026-09-14 01:51:26.571518

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8885e66aab9'
down_revision: str | Sequence[str] | None = '879e067e67d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_text_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation_id')
    )
    op.create_table('full_text_suggestion_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_text_suggestion_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_field_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_field_id'], ['extraction_fields.id'], ),
    sa.ForeignKeyConstraint(['full_text_suggestion_id'], ['full_text_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_text_suggestion_id', 'extraction_field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('full_text_suggestion_values')
    op.drop_table('full_text_suggestions')
    # ### end Alembic commands ###
