"""create ai suggestions and screening decisions tables

Revision ID: f1881f64c6ee
Revises: 348d28e9eeff
Create Date: 2026-09-13 13:56:55.240476

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1881f64c6ee'
down_revision: str | Sequence[str] | None = '348d28e9eeff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation_id')
    )
    op.create_table('screening_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_decisions')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
